name: 快速生成前后端部署所需文件

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
     - uses: actions/checkout@v4

     - name: 安装所需依赖
       run: |
         sudo apt-get update
         sudo -E apt-get -y -qq install git openjdk-17-jdk maven nodejs npm
         mkdir -p $GITHUB_WORKSPACE/buildproject_workspace

     - name: 下载项目源码
       run: |
         cd $GITHUB_WORKSPACE/buildproject_workspace/
         git clone https://github.com/lijilong34/orderfood.git
         
     - name: 开始编译后端项目
       run: |
         cd $GITHUB_WORKSPACE/buildproject_workspace/orderfood/orderfoodafter/
         mvn clean package -DskipTests
  
     - name: 开始编译前端项目
       run: |                                # 这里修复了缩进
         cd $GITHUB_WORKSPACE/buildproject_workspace/orderfood/orderfootbefore/
         npm install
         npm run build

     - name: 上传后端项目
       uses: actions/upload-artifact@v4
       with:
         name: orderfoodafter-$(date +%s)-SNAPSHOT.jar
         path: $GITHUB_WORKSPACE/buildproject_workspace/orderfood/orderfoodafter/target/orderfoodafter-*-SNAPSHOT.jar

     - name: 上传前端项目
       uses: actions/upload-artifact@v4
       with:
         name: orderfootbefore-$(date +%s)
         path: $GITHUB_WORKSPACE/buildproject_workspace/orderfood/orderfootbefore/dist/*
